// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_MsTHo6Bk56VX7TKfr4Nt_FiRIZjjd-Q',
    appId: '1:423443673707:web:433e7f51b4a677e124f72e',
    messagingSenderId: '423443673707',
    projectId: 'medicine-reminder-system-32cd9',
    authDomain: 'medicine-reminder-system-32cd9.firebaseapp.com',
    storageBucket: 'medicine-reminder-system-32cd9.firebasestorage.app',
    measurementId: 'G-WL1M870426',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7d9jGapzR94L7iKoFf7nfZUlkj7fNho0',
    appId: '1:423443673707:android:612775c043cdf72f24f72e',
    messagingSenderId: '423443673707',
    projectId: 'medicine-reminder-system-32cd9',
    storageBucket: 'medicine-reminder-system-32cd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtCix_IP_l5I793jw_1k4MX3fK7QK_NFc',
    appId: '1:423443673707:ios:2807314a05b9df5b24f72e',
    messagingSenderId: '423443673707',
    projectId: 'medicine-reminder-system-32cd9',
    storageBucket: 'medicine-reminder-system-32cd9.firebasestorage.app',
    iosBundleId: 'com.example.medicineReminderSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtCix_IP_l5I793jw_1k4MX3fK7QK_NFc',
    appId: '1:423443673707:ios:2807314a05b9df5b24f72e',
    messagingSenderId: '423443673707',
    projectId: 'medicine-reminder-system-32cd9',
    storageBucket: 'medicine-reminder-system-32cd9.firebasestorage.app',
    iosBundleId: 'com.example.medicineReminderSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_MsTHo6Bk56VX7TKfr4Nt_FiRIZjjd-Q',
    appId: '1:423443673707:web:4fd54dde319d8c4e24f72e',
    messagingSenderId: '423443673707',
    projectId: 'medicine-reminder-system-32cd9',
    authDomain: 'medicine-reminder-system-32cd9.firebaseapp.com',
    storageBucket: 'medicine-reminder-system-32cd9.firebasestorage.app',
    measurementId: 'G-E5FPLLHBW2',
  );
}
